### ISSUE TITLE
Uploading Data from my local

### ISSUE THREAD

**Issue by salacsoft** [hansenms/FhirLoader#1]
I used synthea to generate data and upload it using FhirLoader with my client credentials. I got the output from my terminal(Attached Image), But as I get request using Postman to Observation I did not get any records, I tried to manually Post one on the json in Observation.ndjson it works. but I dont know why there is no records from uploading. Can you help me figure out what I am missing?

**Comment by hansenms** [comment]
It looks like there are records being uploaded. How are you determining that there are no records?

**Comment by salacsoft** [comment]
> It looks like there are records being uploaded. How are you determining that there are no records?

I tried to get Request using postman , i only get this response

**Comment by hansenms** [comment]
It's hard to say based on the data provided here. To me it looks like you are getting resources in because the loader is reporting some resources per second (but there could be some bug, of course). 

My debugging steps would be to search the root of the FHIR service:

```http
GET {{base_url}}/
```

And see if there are any resources in there. 

I would then open something like Fiddler (or similar tool) to see the requests going to the FHIR service and make sure you get 200 and 201 requests. 

You can hook up audit logging to the service:

https://docs.microsoft.com/en-us/azure/healthcare-apis/enable-diagnostic-logging

Finally, I would also advice that you turn up the RUs on the service when bulk loading. Looks like you still have it set at 400. That said, that should not really affect the results here.

**Comment by salacsoft** [comment]
> Fiddler

okay I will try to  use fiddler, 

how can  I check if there are resources what button should I click? 

by the way I can Post to the Claim Resource in Postman and get the record in postman also.

**Comment by hansenms** [comment]
There is no way to check in the portal.  Do a GET to the root as I suggested above

**Comment by salacsoft** [comment]
> There is no way to check in the portal. Do a GET to the root as I suggested above

okay Ill try it. fiddler is still downloading.

**Comment by hansenms** [comment]
I’m also a little curious, if you are saying you are able to POST claim resources with postman, why is that query coming up empty? Maybe double check you are uploading to the right FHIR service.

**Comment by salacsoft** [comment]
> I’m also a little curious, if you are saying you are able to POST claim resources with postman, why is that query coming up empty? Maybe double check you are uploading to the right FHIR service.

the end point URL I Used is the same on the endpoint I used in postman. this is what I am getting from get request to the root

{
    "resourceType": "Bundle",
    "id": "69c4f8c8b70d9946bdd1d802a87fdd8f",
    "meta": {
        "lastUpdated": "2020-05-19T05:40:15.7868477+00:00"
    },
    "type": "searchset",
    "link": [
        {
            "relation": "next",
            "url": "https://test-staging.azurehealthcareapis.com/?ct=A4L1Av
C96UC8vLy9QL1hNa0QvOC84L0lrRC8vUC9QSWtDZi8vLzVJa0R6L3ovL0UwRC9mLzcvNS84UlFQL1AiLCJyYW5nZSI6eyJtaW4iOiIiLCJtYXgiOiJGRiJ9fQ%3D%3D"
        },
        {
            "relation": "self",
            "url": "https://test-staging.azurehealthcareapis.com/"
        }
    ],
    "entry": [
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/CarePlan/********-27b1-41e2-86dd-fa65b0203c1a",
            "resource": {
                "resourceType": "CarePlan",
                "id": "*********-27b1-41e2-86dd-fa65b0203c1a",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-01T13:58:52.78+00:00"
                },
                "status": "active",
                "intent": "plan",
                "subject": {
                    "reference": "Group",
                    "display": "Lea Pfeffer"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/CarePlan/********-c29b-43a9-a46b-fd2dbd175309",
            "resource": {
                "resourceType": "CarePlan",
                "id": "1ff82263-c29b-*********175309",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-01T14:00:39.228+00:00"
                },
                "status": "active",
                "intent": "plan",
                "subject": {
                    "reference": "Group",
                    "display": "Lauretta Ryan"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/DocumentReference/******-ef10-4318-a40c-f29067a35cde",
            "resource": {
                "resourceType": "DocumentReference",
                "id": "*******-ef10-4318-a40c-f29067a35cde",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-01T14:00:40.337+00:00"
                },
                "status": "current",
                "type": {
                    "coding": [
                        {
                            "system": "http://loinc.org",
                            "code": "34108-1",
                            "display": "Outpatient Note"
                        }
                    ]
                },
                "content": [
                    {
                        "attachment": {
                            "contentType": "text/plain",
                            "language": "en-US",
                            "url": "http://localhost:9556/svc/fhir/Binary/1e404af3-077f-4bee-b7a6-a9be97e1ce32",
                            "title": "Physical",
                            "creation": "2005-12-24"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/CarePlan/*******-4ac5-4bc9-a4b6-5e7b99bfb064",
            "resource": {
                "resourceType": "CarePlan",
                "id": "********-4ac5-4bc9-a4b6-****",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:25.201+00:00"
                },
                "status": "active",
                "intent": "plan",
                "subject": {
                    "reference": "Group",
                    "display": "Norris Walter"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/DocumentReference/*****-2cc5-4dc3-a7d9-*****",
            "resource": {
                "resourceType": "DocumentReference",
                "id": "****-2cc5-4dc3-a7d9-********",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:26.483+00:00"
                },
                "status": "current",
                "content": [
                    {
                        "attachment": {
                            "contentType": "image/jpeg",
                            "url": "BrokerUploads/765/companyExternalPlans-9YpjTn3401688_vendor_pic.jpg",
                            "title": "3401688_vendor_pic.jpg"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/CarePlan/*-****-41aa-80b5-e35a951c3210",
            "resource": {
                "resourceType": "CarePlan",
                "id": "*******-3f1f-41aa-******-e35a951c3210",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:27.577+00:00"
                },
                "status": "active",
                "intent": "plan",
                "subject": {
                    "reference": "Group",
                    "display": "Mr. Laron Glover PhD"
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/DocumentReference/*****-2eab-4384-8fe7-*****",
            "resource": {
                "resourceType": "DocumentReference",
                "id": "*****-2eab-4384-8fe7-4ad8c42c50a8",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:27.838+00:00"
                },
                "status": "current",
                "content": [
                    {
                        "attachment": {
                            "contentType": "image/jpeg",
                            "url": "BrokerUploads/765/companyExternalPlans-yuLrWO3401686_vendor_pic.jpg",
                            "title": "3401686_vendor_pic.jpg"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/CarePlan/*********721-a045-4cdfcdfb584e",
            "resource": {
                "resourceType": "CarePlan",
                "id": "******-477b-4721-a045-4cdfcdfb584e",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:28.792+00:00"
                },
                "status": "active",
                "intent": "plan",
                "subject": {
                    "reference": "Group",
                    "display": "Besides."
                }
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/DocumentReference/************-9243-57fc433f6bac",
            "resource": {
                "resourceType": "DocumentReference",
                "id": "48e34552-ba11-4a1d-********",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:29.001+00:00"
                },
                "status": "current",
                "content": [
                    {
                        "attachment": {
                            "contentType": "image/jpeg",
                            "url": "BrokerUploads/766/companyExternalPlans-tqTN1i3401689_vendor_pic.jpg",
                            "title": "3401689_vendor_pic.jpg"
                        }
                    }
                ]
            },
            "search": {
                "mode": "match"
            }
        },
        {
            "fullUrl": "https://test-staging.azurehealthcareapis.com/CarePlan/***********-a10a-9e57d89f31de",
            "resource": {
                "resourceType": "CarePlan",
                "id": "27ad42b0-1259-4cca-************",
                "meta": {
                    "versionId": "1",
                    "lastUpdated": "2020-04-02T00:12:29.745+00:00"
                },
                "status": "active",
                "intent": "plan",
                "subject": {
                    "reference": "Group",
                    "display": "Alice."
                }
            },
            "search": {
                "mode": "match"
            }
        }
    ]
}

**Comment by salacsoft** [comment]
can you show me sample, what should i see when I get request on the root service?

**Comment by hansenms** [comment]
That looks like what you should be getting at the root. So for the

```
GET {{base_url}}/Claim
```

Why is it empty when you say that you inserted a claim using Postman?

What about:

```
GET GET {{base_url}}/Patient
```

**Comment by salacsoft** [comment]
> That looks like what you should be getting at the root. So for the
> 
> ```
> GET {{base_url}}/Claim
> ```
> 
> Why is it empty when you say that you inserted a claim using Postman?
> 
> What about:
> 
> ```
> GET GET {{base_url}}/Patient
> ```

 GET {{base_url}}/Patient has data but none in the response is from the generated record from the synthea, I tried to search id from generated record, but I havent found it from the response. 
I am also wondering why.

**Comment by hansenms** [comment]
It is difficult to help debug based on the information here. I cannot reproduce the behavior you are describing.

1; When you say that you can add a Claim resource, why is the Claim search empty?
1. What do you see in Fiddler when doing the import?

**Comment by salacsoft** [comment]
Unfortunately I cant install the fiddler to my ubuntu pc, is there any possible cause why I cant see the uploaded data?  I am thinking maybe data are being uploaded but in difference organization and my account does not have access in that organization something like that.

**Comment by hansenms** [comment]
I think we need to set up time to walk through this. Can you email me: mihansen AT microsoft.com. We will work through this.
