### ISSUE TITLE
Fhir uploading CCDA

### ISSUE THREAD

**Issue by salacsoft** [hansenms/FhirLoader#2]
How can I upload the ccda data in out Fhir in azure? I can upload the json file inside the output/fhir folder, so I tried to change the path to CCDA folder but I did not get any response.

**Comment by hansenms** [comment]
This is a FHIR uploader, it does not deal with C-CDA.

**Comment by salacsoft** [comment]
oh okay, the synthea also generating ccda i though it also include that. is there other tools to upload c-cda in fhir? thank you.

**Comment by hansenms** [comment]
Synthea also generates CSV and other stuff, but this tool is for FHIR. It is not specifically for Synthea. I don't know of any tool that loads C-CDA directly into FHIR. They are different formats. 

We have another project called FHIR converter: https://github.com/Microsoft/fhir-converter. It will include C-CDA to FHIR conversion in the next few weeks. You could use that to convert C-CDA to FHIR and then load the FHIR data into the FHIR server. 

Again, I would recommend asking these kinds of generic FHIR/healthcare data questions on Stackoverflow or the Zulip chat.
